name: CI/CD Pipleline

on: push
   # push:
   #    branches: [ "env/prd" ]
   # pull_request:
   #    branches: [ "env/prd" ]
   #workflow_dispatch:

jobs:
   AWS_Connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Connect to AWS Account'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

   Terraform_Plan:
    needs: [AWS_Connection]
    runs-on: ubuntu-latest
    steps:
      - name: Terraform_Plan
        run: echo "Terraform_Plan" exit code 1

   Terraform_Apply:
    needs: [ AWS_Connection, Terraform_Plan ]
    runs-on: ubuntu-latest
    steps:
      - name: Push Content
        run: echo '${{ toJSON(github.event) }}' | jq
      - name: Terraform_Apply
        if: github.ref == 'refs/heads/env/prd' && github.event_name == 'push'
        run: echo "Terraform_Apply"
