name: CI/CD Pipleline

on:
   # // push:
   # //   branches: [ "env/prd" ]
   # // pull_request:
   # //   branches: [ "env/prd" ]
       
   workflow_dispatch:

jobs:
  AWS Connection:
    runs-on: ubuntu-latest
    steps:
      - name: 'Connect to AWS Account'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
