# This is a basic workflow to help you get started with Actions

name: docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "env/prd" branch
  # push:
  #   branches: [ "env/prd" ]
  # pull_request:
  #   branches: [ "env/prd" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and Push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/githubactions
      # -
      #   name: Build
      #   run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/githubactions:latest .
      # -
      #   name: Push
      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/githubactions:latest
