name: Label Issues

on:
  issues:
    types:
      - opened
  workflow_run:
    workflows: ["Issues Creation"]
    branches: [ "env/prd" ]
    types: 
      - completed

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label Issue
        run: gh issue label add ${{ github.event.issue.number }} "Approve for test"
