name: Label Issues

on:
  workflow_run:
    workflows: ["Issues Creation"]
    branches: [ "env/prd" ]
    types: 
      - completed
      
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label Issue
        run: gh issue edit ${{ github.event.issue.number }} --add-label "Approve for test"
