name: Label and Comment issues

on:
  issues:
    types:
      - opened
      
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.ACCESS_TOKEN }}
          assignees: AjinkyaChandekar

  label_comment_issues:
    needs: [auto-assign]
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      GH_REPO: ${{ github.repository }}
      NUMBER: ${{ github.event.issue.number }}
    steps:
      - name: Assign Label "Approve for test"
        run: gh issue edit "$NUMBER" --add-label $LABELS_01
        env:
          LABELS_01: Approve for test
      - name: Comment issue "Approved"
        run: gh issue comment "$NUMBER" --body "Approved"
          
      - name: Assign Label "Sign Off Test"
        run: |
          gh issue edit "$NUMBER" --remove-label $LABELS_01
          gh issue edit "$NUMBER" --add-label $LABELS_02
        env:
          LABELS_02: Sign Off Test
      - name: Comment Issue "Validated"
        run: gh issue comment "$NUMBER" --body "Validated"
        
      - name: Assign Label "Approve for PROD"
        run: |
          gh issue edit "$NUMBER" --remove-label $LABELS_02
          gh issue edit "$NUMBER" --add-label $LABELS_03
        env:
          LABELS_03: Approve for PROD
      - name: Comment Issue "Approved"
        run: gh issue comment "$NUMBER" --body "Approved"
      
      
# name: Label Issues

# on:
#   issues:
#     types:
#       - opened
#   # workflow_run:
#   #   workflows: ["Issues Creation"]
#   #   branches: [ "env/prd" ]
#   #   types: 
#   #     - completed
#   workflow_dispatch:

# jobs:
#   label_issues:
#     runs-on: ubuntu-latest
#     permissions:
#       issues: write
#     steps:
#       - name: Label Issue
#         run: gh issue edit 25 --add-label "Approve for test"
#         env:
#           token: ${{ secrets.ACCESS_TOKEN }}
