name: Issue Assignment

on:
  issues:
    types: [opened]
    
  workflow_dispatch:

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          assignees: AjinkyaChandekar
