name: Issue Assignment

on:
  workflow_run:
    workflows: ["Issues Comment"]
    branches: [ "env/prd" ]
    types: 
      - completed
  issues:
    types: [opened]
    
  workflow_dispatch:

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.ACCESS_TOKEN }}
          assignees: AjinkyaChandekar
