name: Issues Creation

on:
   push:
      branches: [ "env/prd" ]
      
   workflow_dispatch:

jobs:
   create_issue:
      runs-on: ubuntu-latest
      steps:
      - name: "Dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq

      - name: Create an Issue
        uses: dacbd/create-issue-action@main
        with:
           token: ${{ secrets.ACCESS_TOKEN }}
           title: <Git-Repo2> <Branch-Name>
           body: Approved
