# name: Label Issues

# on:
#   issues:
#     types:
#       - opened
#   # workflow_run:
#   #   workflows: ["Issues Creation"]
#   #   branches: [ "env/prd" ]
#   #   types: 
#   #     - completed
#   workflow_dispatch:

# jobs:
#   label_issues:
#     runs-on: ubuntu-latest
#     permissions:
#       issues: write
#     steps:
#       - name: Label Issue
#         run: gh issue edit 25 --add-label "Approve for test"
#         env:
#           token: ${{ secrets.ACCESS_TOKEN }}

name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: Approve for test
