name: Label and Comment issues
on:
  issues:
    types:
      - opened
jobs:
  label_comment_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: Approve for test
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: Sign Off Test
      - run: gh issue comment "$NUMBER" --body "Validated"
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: Approve for PROD
      - run: gh issue comment "$NUMBER" --body "Approved"
      
      
# name: Label Issues

# on:
#   issues:
#     types:
#       - opened
#   # workflow_run:
#   #   workflows: ["Issues Creation"]
#   #   branches: [ "env/prd" ]
#   #   types: 
#   #     - completed
#   workflow_dispatch:

# jobs:
#   label_issues:
#     runs-on: ubuntu-latest
#     permissions:
#       issues: write
#     steps:
#       - name: Label Issue
#         run: gh issue edit 25 --add-label "Approve for test"
#         env:
#           token: ${{ secrets.ACCESS_TOKEN }}
