name: Test Issue Creation

on:
  push:
    branches: [ "env/prd" ]

  workflow_dispatch:

jobs:
   create_assign_label_issue:
      runs-on: ubuntu-latest
      steps:
      - name: "Dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq

      - name: Create an Issue
        run: |
          echo "Creating the issue..."
          gh issue create -t '${{ github.event.repository.name }} ${{ github.event.repository.default_branch }}' -b "Approved"
          env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

# name: Test Issue
# on:
#   issues:
#     types:
#       - reopened
#       - opened
# jobs:
#   label_issues:
#     runs-on: ubuntu-latest
#     permissions:
#       issues: write
#     steps:
#       - run: gh issue edit "$NUMBER" --add-label "$LABELS"
#         env:
#           GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#           GH_REPO: ${{ github.repository }}
#           NUMBER: ${{ github.event.issue.number }}
#           LABELS: Approve for test
