name: Test Issue Creation

on:
  push:
    branches: [ "env/prd" ]

  workflow_dispatch:

jobs:
   create_assign_label_issue:
      runs-on: ubuntu-latest
      steps:
      - name: "Dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq

      - name: Create an Issue
        run: |
          echo "Creating the issue..."
          gh issue create -t '${{ github.event.repository.name }} ${{ github.event.repository.default_branch }}' -b "Approved"
