name: Test Issue Creation

on:
  push:
    branches: [ "env/prd" ]

  workflow_dispatch:


jobs:
   create_assign_label_issue:
      runs-on: ubuntu-latest
      steps:
        - uses: nashmaniac/create-issue-action@v1.2
          name: Create Issue Action
          with:
            title: '${{ github.event.repository.name }} ${{ github.event.repository.default_branch }}'
            token: ${{secrets.ACCESS_TOKEN}}
            assignees: ${{github.actor}}
            labels: Approve for test
            body: Approved

# name: Test Issue
# on:
#   issues:
#     types:
#       - reopened
#       - opened
# jobs:
#   label_issues:
#     runs-on: ubuntu-latest
#     permissions:
#       issues: write
#     steps:
#       - run: gh issue edit "$NUMBER" --add-label "$LABELS"
#         env:
#           GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#           GH_REPO: ${{ github.repository }}
#           NUMBER: ${{ github.event.issue.number }}
#           LABELS: Approve for test
